print("hello world")
print("introducing myself shriti")
print("so the jorney begins")
print("lets do something crazy")
print("build,dont talk")
print("53")
print("40+33")
print("50-45")
print(44+89)
print(78-67)